### ISSUE TITLE
Missing endpoint: /rest/db/revert 

### ISSUE THREAD

**Issue by NunoBento** [JodusNodus/node-syncthing#11]
Hello, I'm using node-syncthing and noticed the revert endpoint was missing.

You already fixed one of these ([add override endpoint](https://github.com/JodusNodus/node-syncthing/commit/7d0f657ea4419d38f2a835ddabd163701c785780#diff-6d186b954a58d5bb740f73d84fe39073)), and the changes are minimal for what I've seen.
Can you please add it ?

https://docs.syncthing.net/rest/db-revert-post.html

**Comment by JodusNodus** [comment]
Will be published in the next release.

**Comment by JodusNodus** [comment]
Fixed in published version `3.3.7`

**Comment by NunoBento** [comment]
Thanks! Already using it
