### ISSUE TITLE
How to test the event listener?

### ISSUE THREAD

**Issue by fiatjaf** [JodusNodus/node-syncthing#4]
I want to propose a change in which we can set the client to only start listening to events (polling, actually) after some time, instead of only at instantiation time, but I'm not experienced enough in Syncthing to know the inner workings of events. Can you give me a suggestion on how should I manually trigger events (perhaps only one or two of them) so I can test the event listener?

**Comment by JodusNodus** [comment]
I would get the config with st.system.getConfig and then set the same config with st.system.setConfig. And then a configSaved event would then be thrown.
